resources:
- secret.yaml
namespace: ns
secretGenerator:
- name: example-secret
  literals:
  - example1=foo
  - example2=bar
  - example3=baz
configMapGenerator:
- name: not-a-secret
  literals:
  - FOO=Bar
generatorOptions:
  labels:
    type: generated
  annotations:
    note: generated
configMapGenerator:
- name: also-not-a-secret
  namespace: ns
  literals:
  - BAR=Foo
secretGenerator:
- name: example-secret-2
  namespace: ns
  literals:
  - example1=foo
  - example2=bar
  - example3=baz